services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony-php
    working_dir: /var/www/backend
    volumes:
      - ./backend:/var/www/backend
    networks:
      - app-network
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: symfony-nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/backend
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - php

  db:
    image: mysql:8.0
    container_name: symfony-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: controle_presenca
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  react:
    container_name: react-frontend
    build:
      context: ./frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - app-network
    command: ["npm", "run", "dev"]

networks:
  app-network:

volumes:
  db-data:
